### ISSUE TITLE
Ō in Otara causing encoding error

### ISSUE THREAD

**Issue by damanlikesham** [tim-fan/location_of_interest_checker#1]
After trying to run the script on my location history using the command

`location_of_interest_checker Location\ History.json results.csv`

 the output reports

`File "/usr/local/lib/python3.6/dist-packages/location_of_interest_checker/location_of_interest_checker.py", line 184, in print_location_of_interest
    print(f"Event: {location.Event}\n"
UnicodeEncodeError: 'ascii' codec can't encode character '\u014c' in position 26: ordinal not in range(128)` 

I guess that'd be the Ō in Ōtara doing that in the locations of interest.

Cheers.

**Comment by tim-fan** [comment]
Hi, thanks for giving it a go!

I imagine its something along the lines of https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20. I'll look into it a bit more at lunch time.

I'm not able to reproduce the issue - I'm able to print all the locations of interest, including those in Ōtara.

I'm testing with:
```
$ python --version
Python 3.8.10
```
Are you using a different python version?

**Comment by damanlikesham** [comment]
Ah, I'm using Python 2.7.17 which uses ASCII encoding by default. That'll be my issue.
Thanks for making this, looking forward to seeing what you do with it.

**Comment by tim-fan** [comment]
Ah yep, thanks again for giving it a go, but I don't think I'll spend time trying to support 2.7. Are you able to upgrade?

**Comment by damanlikesham** [comment]
Yep, changed to Python 3.6 and updated system locale to en_NZ.UTF-8 and it works perfectly.

Cheers :)

**Comment by tim-fan** [comment]
Glad to hear it!
