### ISSUE TITLE
Update location of interest data source after August

### ISSUE THREAD

**Issue by tim-fan** [tim-fan/location_of_interest_checker#3]
Current location of interest data is sourced from 
https://raw.githubusercontent.com/minhealthnz/nz-covid-data/main/locations-of-interest/august-2021/locations-of-interest.geojson

Based on the url, this will likely only be valid for August - looks like another file will be added for September.

When the September datafile is added, update this script to use both August and September sources.

**Comment by dukestraykker** [comment]
The date is for specifying the outbreak not the current month, this should be fine for this outbreak instance

**Comment by tim-fan** [comment]
Oh right, thanks for the heads up! I hope if you're using this tool that it's working well for you 👍

**Comment by dukestraykker** [comment]
Yes it is working wonderfully - I despise the Covid app, and had been using
my google location history to manually ensure I checked locations, so when
this came up it sped everything up tremendously. I run it every 60 minutes
for mine and my wife's data (manually exported once a week) and have home
assistant (HASS.IO) alert me if the number is less than 0.2 KM away.

**Comment by tim-fan** [comment]
Haha that's awesome, glad it could be of use, and I hope your assistant doesn't give you any alerts!
